# Generated by Django 3.1.3 on 2021-03-31 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_auto_20210331_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='group_index',
            new_name='group_name',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='set_index',
            new_name='set_name',
        ),
    ]
