# Generated by Django 3.1.3 on 2021-03-31 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20210401_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='set_name',
        ),
        migrations.AddField(
            model_name='participant',
            name='group_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='set_index',
            field=models.IntegerField(default=0),
        ),
    ]
