# Generated by Django 3.1.3 on 2021-04-15 17:31

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_event_required_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_fields',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('GENDER', 'Пол'), ('BIRTH_YEAR', 'Год рождения'), ('CITY', 'Город'), ('TEAM', 'Команда'), ('GRADE', 'Разряд')], default='GENDER,BIRTH_YEAR,CITY,TEAM', max_length=33, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='required_fields',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BIRTH_YEAR', 'Год рождения'), ('CITY', 'Город'), ('TEAM', 'Команда')], default=None, max_length=20, null=True),
        ),
    ]
