# Generated by Django 3.1.3 on 2021-04-17 11:03

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_auto_20210415_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_view_route_color',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_view_route_grade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_view_route_score',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accent',
            name='accent',
            field=models.CharField(choices=[('NO', 'NO'), ('FL', 'FLASH'), ('RP', 'REDPOINT')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_fields',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('gender', 'Пол'), ('birth_year', 'Год рождения'), ('city', 'Город'), ('team', 'Команда'), ('grade', 'Разряд')], default='gender,birth_year,city,team', max_length=33, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='required_fields',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('birth_year', 'Год рождения'), ('city', 'Город'), ('team', 'Команда')], default=None, max_length=20, null=True),
        ),
    ]
