# Generated by Django 3.1.3 on 2021-09-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_event_last_calc_results_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='accents',
            field=models.JSONField(default={}),
        ),
    ]
