# Generated by Django 3.1.3 on 2021-09-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_participant_accents'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='accents_num',
            field=models.JSONField(default={}),
        ),
    ]
