# Generated by Django 3.1.3 on 2021-10-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0043_remove_event_last_calc_results_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gym',
            field=models.CharField(default='Скалодром', max_length=128),
            preserve_default=False,
        ),
    ]
