# Generated by Django 3.1.3 on 2022-03-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0049_event_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='group_list',
            field=models.CharField(default='Общая группа', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='routes_num',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='set_list',
            field=models.CharField(default='Общий сет', max_length=200),
        ),
    ]
