# Generated by Django 3.1.3 on 2022-04-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0051_event_is_update_results_after_enter'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='place',
            field=models.IntegerField(default=0),
        ),
    ]
