# Generated by Django 4.0.4 on 2022-10-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0055_event_is_update_result_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participant_min_age',
            field=models.IntegerField(default=0),
        ),
    ]
