# Generated by Django 4.0.4 on 2022-10-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0056_event_participant_min_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='yoomoney_wallet_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
