# Generated by Django 4.0.4 on 2022-10-16 20:29

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0059_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_fields',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('gender', 'Пол'), ('birth_year', 'Год рождения'), ('city', 'Город'), ('team', 'Команда'), ('grade', 'Разряд'), ('email', 'Email')], default='gender,birth_year,city,team', max_length=39, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='required_fields',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('birth_year', 'Год рождения'), ('city', 'Город'), ('team', 'Команда'), ('email', 'Email')], default=None, max_length=26, null=True),
        ),
    ]
