# Generated by Django 4.0.4 on 2022-10-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0060_participant_email_alter_event_registration_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
