# Generated by Django 4.0.4 on 2022-10-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_customuser_yoomoney_secret_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='yoomoney_wallet_id',
        ),
        migrations.AddField(
            model_name='event',
            name='is_pay',
            field=models.BooleanField(default=False),
        ),
    ]
