# Generated by Django 4.0.4 on 2022-10-22 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_yoomoney_wallet_id_event_is_pay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='is_pay',
            new_name='is_pay_allowed',
        ),
    ]
