# Generated by Django 4.0.8 on 2022-11-16 06:47

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_score_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='score_json',
            field=models.JSONField(default=events.models._get_default_route_score_json),
        ),
    ]
