# Generated by Django 4.0.8 on 2022-11-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_score_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='flash_points',
        ),
        migrations.AddField(
            model_name='event',
            name='flash_points_pc',
            field=models.IntegerField(default=25),
        ),
    ]
