# Generated by Django 4.0.8 on 2022-11-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_is_premium_event_is_premium_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='premium_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
