# Generated by Django 4.0.8 on 2022-11-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_customuser_premium_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='premium_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
