# Generated by Django 4.0.8 on 2022-11-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_premium_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
    ]
