# Generated by Django 4.0.8 on 2022-12-15 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_event_description_alter_event_gym_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='is_premium_used',
            new_name='is_expired',
        ),
    ]
