# Generated by Django 4.0.8 on 2022-12-15 13:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_participant_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='counted_routes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
