# Generated by Django 4.0.8 on 2023-03-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_paydetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='french_accents',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='score_type',
            field=models.CharField(choices=[('SUM', 'Сумма баллов'), ('PROP', 'От количества пролазов'), ('TBL', 'По таблице категорий'), ('NUM', 'По количеству Всего/Flash'), ('FR', 'Французская система')], default='SUM', max_length=4),
        ),
        migrations.AlterField(
            model_name='participant',
            name='accents',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
