# Generated by Django 4.0.8 on 2023-03-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_paydetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reg_type_list',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='reg_type_num',
            field=models.IntegerField(default=1),
        ),
    ]
