# Generated by Django 4.0.8 on 2023-03-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_participant_reg_type_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
