# Generated by Django 4.0.8 on 2023-03-29 07:39

from django.db import migrations
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_event_price_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_fields',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('gender', 'Пол'), ('birth_year', 'Год рождения'), ('city', 'Город'), ('team', 'Команда'), ('grade', 'Разряд'), ('email', 'Email'), ('phone_number', 'Телефон')], default='gender,birth_year,city,team', max_length=52, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='required_fields',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('birth_year', 'Год рождения'), ('city', 'Город'), ('team', 'Команда'), ('email', 'Email'), ('phone_number', 'Телефон')], default=None, max_length=39, null=True),
        ),
    ]
