# Generated by Django 4.0.8 on 2023-03-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_participant_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pay_type',
            field=models.CharField(blank=True, choices=[('yoomoney', 'Кошелек Yoomoney'), ('sbp', 'СБП (QR-код)')], default='yoomoney', max_length=20),
        ),
    ]
