# Generated by Django 4.0.8 on 2023-03-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_event_pay_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pay_type',
            field=models.CharField(choices=[('yoomoney', 'Кошелек Yoomoney'), ('sbp', 'СБП (QR-код)')], default='yoomoney', max_length=20),
        ),
    ]
