# Generated by Django 4.0.8 on 2023-03-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_alter_event_pay_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
