# Generated by Django 4.0.8 on 2023-04-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_participant_french_score'),
        ('events', '0023_alter_event_price'),
    ]

    operations = [
    ]
