# Generated by Django 3.1.3 on 2021-03-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_auto_20210331_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='group_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='set_index',
            field=models.IntegerField(default=0),
        ),
    ]
