# Generated by Django 4.0.8 on 2023-04-03 12:38

import dataclasses
from django.db import migrations

from events.services import Accent
from events.models import _get_blank_french_accents_json


def participants_change_to_french(apps, schema_editor):
    Participant = apps.get_model("events", "Participant")
    for p in Participant.objects.all():
        if p.is_entered_result:
            french_accents = {}
            for no, accent in p.accents.items():
                a = Accent(top=int(accent), zone=0)
                french_accents.update({no: dataclasses.asdict(a)})
            p.french_accents = french_accents
        else:
            p.french_accents = _get_blank_french_accents_json()
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_merge_20230403_1537'),
    ]

    operations = [
        migrations.RunPython(participants_change_to_french),
    ]
