# Generated by Django 4.0.8 on 2023-04-03 12:38

import dataclasses
from django.db import migrations

from events.services import Accent


def participants_change_to_french():
    Participant = apps.get_model("events", "Participant")
    for p in Participant.objects.all():
        if p.is_entered_result:
            french_accents = {}
            for no, accent in p.accents.items():
                a = Accent(top=int(accent), zone=0)
                french_accents.update({no: dataclasses.asdict(a)})
            p.french_accents = french_accents
            p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_merge_20230403_1537'),
    ]

    operations = [
        migrations.RunPython(participants_change_to_french),
    ]
