# Generated by Django 3.1.3 on 2021-03-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20210331_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='group_index',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='set_index',
            field=models.CharField(default='', max_length=100),
        ),
    ]
