# Generated by Django 4.0.8 on 2023-04-04 13:51

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_auto_20230403_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='accents',
            field=models.JSONField(blank=True, default=events.models._get_blank_accents_json, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='french_accents',
            field=models.JSONField(blank=True, default=events.models._get_blank_french_accents_json, null=True),
        ),
    ]
