# Generated by Django 4.0.8 on 2023-04-11 08:31

import django.contrib.postgres.fields
from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_alter_participant_accents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='counted_routes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=events.models._get_default_array, null=True, size=None),
        ),
    ]
