# Generated by Django 4.0.8 on 2024-09-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_alter_participant_counted_routes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_premium',
            field=models.BooleanField(default=True),
        ),
    ]
