# Generated by Django 3.1.3 on 2021-04-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_auto_20210401_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='set_max_participants',
            field=models.IntegerField(default=0),
        ),
    ]
