# Generated by Django 4.0.8 on 2026-03-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_alter_event_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_end',
            field=models.DateField(null=True),
        ),
    ]
