# Generated by Django 3.1.3 on 2021-04-15 17:11

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_auto_20210403_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='required_fields',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=None, max_length=9),
        ),
    ]
