# Generated by Django 6.0.7 on 2026-07-17 14:38

import django.contrib.postgres.fields
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_alter_event_date_end'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE events_event ALTER COLUMN registration_fields TYPE varchar(20)[] USING string_to_array(registration_fields, ',');",
            reverse_sql="ALTER TABLE events_event ALTER COLUMN registration_fields TYPE varchar(52) USING array_to_string(registration_fields, ',');"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE events_event ALTER COLUMN required_fields TYPE varchar(20)[] USING string_to_array(required_fields, ',');",
            reverse_sql="ALTER TABLE events_event ALTER COLUMN required_fields TYPE varchar(39) USING array_to_string(required_fields, ',');"
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('gender', 'Пол'), ('birth_year', 'Год рождения'), ('city', 'Город'), ('team', 'Команда'), ('grade', 'Разряд'), ('email', 'Email'), ('phone_number', 'Телефон')], max_length=20), blank=True, default=events.models._get_default_registration_fields, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='required_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('birth_year', 'Год рождения'), ('city', 'Город'), ('team', 'Команда'), ('email', 'Email'), ('phone_number', 'Телефон')], max_length=20), blank=True, default=list, null=True),
        ),
    ]
