# Generated by Django 6.0.7 on 2026-07-22 10:43

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_alter_event_registration_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_close_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
