# Generated by Django 6.0.8 on 2026-09-19 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_backfill_french_accents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='accents',
        ),
    ]
