# Generated by Django 3.1.3 on 2021-05-09 10:58

import django.contrib.postgres.fields
from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_event_is_without_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='score',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=1.0), size=5), blank=True, default=events.models.get_default_scores, size=2),
        ),
    ]
