# Generated by Django 3.1.3 on 2021-08-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_route_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_separate_score_by_groups',
            field=models.BooleanField(default=False),
        ),
    ]
