# Generated by Django 3.1.3 on 2021-10-13 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_route_score_json'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accent',
        ),
    ]
