# Generated by Django 3.1.3 on 2021-10-13 10:39

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_auto_20211013_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='accents',
            field=models.JSONField(default=events.models._get_blank_json),
        ),
    ]
