# Generated by Django 3.1.3 on 2021-11-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0044_event_gym'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_view_pin_after_registration',
            field=models.BooleanField(default=True),
        ),
    ]
