# Generated by Django 3.1.3 on 2021-12-10 17:48

from django.db import migrations, models

from config import settings


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0045_event_is_view_pin_after_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(default=f'{settings.STATIC_ROOT}/events/img/default_poster.png', upload_to='posters'),
        ),
    ]
