# Generated by Django 3.1.3 on 2021-12-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0047_event_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(default='../static/events/img/default_poster.png', upload_to='posters'),
        ),
    ]
