# Generated by Django 3.1.3 on 2021-12-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0048_auto_20211213_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
