#!/bin/bash
source venv/bin/activate
python manage.py maintenance_mode on
git pull
pip install -r requirements.txt
python manage.py migrate
python manage.py collectstatic --noinput
systemctl restart gunicorn
python manage.py maintenance_mode off
deactivate
