services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - .env.prod
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    # Привязываем порт только к localhost сервера для безопасности
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - /var/www/climbing_events/static:/app/static
      - /var/www/climbing_events/media:/app/media
    env_file:
      - .env.prod
    depends_on:
      - db
    restart: always

volumes:
  postgres_data_prod:
